# Generated by Django 5.0.4 on 2024-05-01 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='interessanteOrte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ortung', models.CharField(max_length=150)),
                ('beschreibung', models.TextField()),
                ('bild', models.ImageField(upload_to='interessanteOrte/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessanteOrte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
