# Generated by Django 5.0.4 on 2024-05-02 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnterlagenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('file', models.FileField(upload_to='Unterlagen/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unterlagen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
